import type { Metadata } from "next";
import LearnPageScaffold from "@/components/LearnPageScaffold";

const APP_URL = process.env.APP_URL || "https://www.tradezerodte.com";

export const metadata: Metadata = {
  title: "Reading the Analysis Tab — Comparing Premarket vs Market-Open",
  description:
    "The Analysis tab is published mid-morning after the open. It compares the premarket plan against the market-open re-grade, surfaces high-probability picks deterministically, and adds an LLM narrative. Here's how to read every row.",
  alternates: { canonical: `${APP_URL}/learn/analysis` },
  openGraph: {
    type: "article",
    url: `${APP_URL}/learn/analysis`,
    title: "Reading the Analysis Tab — Comparing Premarket vs Market-Open",
    description:
      "Comparative analysis tab: high-probability picks rule, lineage labels, grade Δ, direction Δ, and how the narrative fits in.",
  },
};

export default function Page() {
  return (
    <LearnPageScaffold
      title="Reading the Analysis Tab — Comparing Premarket vs Market-Open"
      lead="The Analysis tab is the morning's reconciliation: which premarket trades held up after the opening drive, which got re-graded, which got killed, and which fresh setups appeared at the open. It runs around 10:15 AM ET, after both the premarket scan (8:30) and the market-open scan (9:45) have published. The LLM narrative reads the two side-by-side; the comparison table and the high-probability picks list are computed deterministically — no LLM judgment on the math."
      slug="analysis"
      faqs={[
        {
          question: "What does the Analysis tab show?",
          answer:
            "Three sections: (1) an LLM-written narrative at the top, comparing the premarket bias to what actually happened at the open; (2) a deterministic 'High-probability picks' list that filters to trades that survived both scans cleanly; (3) a full cross-comparison table showing every ticker that appeared in either scan, with grade and direction deltas.",
        },
        {
          question: "What's the rule for 'High-probability picks'?",
          answer:
            "Three conditions must all hold: (1) the ticker appears in BOTH the premarket and market-open scans (no new-at-open, no premarket-only); (2) direction is stable — no flip from put to call, no shift to AVOID, no shift from AVOID; (3) the market-open grade is A− or better, OR the grade was upgraded into the A-tier at the open. The point is to surface setups where the morning re-grading confirmed (or strengthened) the premarket conviction.",
        },
        {
          question: "What does the 'Lineage' column mean in the comparison table?",
          answer:
            "Where the trade came from. 'Both' = appeared in premarket AND market-open (a continued plan). 'New at open' = market-open introduced it (not in premarket — usually an opening-drive opportunity the premarket didn't anticipate). 'Premarket only' = premarket flagged it but market-open dropped it (often because the underlying moved away from the setup).",
        },
        {
          question: "What do ▲ and ▼ symbols in 'Δ Grade' mean?",
          answer:
            "Grade movement from premarket to market-open. ▲ N = upgraded N grade steps (e.g. B+ to A is ▲ 2). ▼ N = downgraded N steps. A single dot (·) = same grade in both scans. A dash (—) = the ticker only appeared in one scan, so there's no delta to compute. Upgrades are green, downgrades are red.",
        },
        {
          question: "What does 'Δ Dir' tell me?",
          answer:
            "How direction changed across scans. 'same' (green) = put stayed put, call stayed call — high conviction. 'flipped' (red) = put → call or call → put, a strong reversal signal. '→ avoid' (red) = market-open downgraded a live setup to AVOID. 'from avoid' = market-open promoted a premarket AVOID into a live trade. Each tells a different story about how the open changed the read.",
        },
        {
          question: "Why is the narrative sometimes empty?",
          answer:
            "The narrative is written by the analysis routine that runs around 10:15 AM ET. If you load the page before 10:15 — or if the routine hasn't run yet for some reason — the narrative section will say 'Narrative is generated by the 10:00 ET analysis routine.' The deterministic table and high-probability picks are available the moment market-open publishes (~9:45) — they don't need the LLM.",
        },
        {
          question: "How do I use this tab in practice?",
          answer:
            "Skim the narrative for the morning's character — was the open in line with the premarket bias, or did it diverge? Then scan the high-probability picks: these are the trades the two scans agreed on with A-tier conviction. Use the full comparison table to spot revisions you should be aware of — anything that flipped direction, anything that dropped to AVOID, anything that got upgraded into the A-tier. The TRADE CARDS tab shows the final merged plan; Analysis tells you HOW the plan evolved.",
        },
        {
          question: "If a trade isn't a 'high-probability pick' should I avoid it?",
          answer:
            "Not necessarily. The filter is conservative on purpose — designed to surface the absolute clearest setups. Plenty of profitable trades won't qualify: a B+ in both scans is solid but doesn't meet the A− threshold; a single-scan opportunity ('New at open') might be the best trade of the day. Use the picks list as the highest-conviction shortlist; use the full comparison table to evaluate the rest.",
        },
        {
          question: "What's the difference between Analysis and the merged Trade Cards?",
          answer:
            "Analysis is about HOW the plan evolved — the narrative and comparison emphasize the transition from premarket to market-open. TRADE CARDS shows the FINAL merged plan — strike, entry, targets, stop, rationale per ticker, with the post-close outcome stamped at the end of the day. Analysis is the 'change log'; Trade Cards is the 'current state'.",
        },
        {
          question: "Why aren't 'avoid' direction trades in the high-probability picks?",
          answer:
            "An 'avoid' is the routine flagging the ticker as untradeable for the day — usually because of unfavorable IV, poor liquidity, an event in the way, or no clean setup. By definition there's no high-probability trade there. The cross-comparison table will still show avoids so you can audit the routine's reasoning, but they're excluded from the picks list since there's nothing to take.",
        },
      ]}
      related={[
        { slug: "trade-cards", title: "Reading the Trade Cards" },
        { slug: "scorecard", title: "Scorecard — Tracking Performance Over Time" },
        { slug: "0dte-options", title: "What is 0DTE Options Trading?" },
        { slug: "weekly-research", title: "Weekly Research Stack" },
      ]}
    >
      <h2>The three sections, top to bottom</h2>
      <ol>
        <li>
          <strong>LLM narrative.</strong> Written by the analysis routine
          around 10:15 AM ET. Reads the premarket and market-open scans
          side-by-side and explains what the open implied — confirmation,
          rotation, or a divergence from the premarket bias.
        </li>
        <li>
          <strong>High-probability picks.</strong> Deterministic. Filters to
          trades that satisfy all three conditions (in both scans · direction
          stable · grade ≥ A−). No LLM judgment — pure rule.
        </li>
        <li>
          <strong>Cross-comparison table.</strong> Every ticker from either
          scan, with lineage, premarket grade + direction, market-open grade +
          direction, grade Δ, direction Δ. The full audit trail.
        </li>
      </ol>

      <h2>Lineage legend</h2>
      <ul>
        <li>
          <strong>Both</strong> (green) — appeared in premarket AND market-open.
          A continued plan. The most common lineage.
        </li>
        <li>
          <strong>New at open</strong> (sky-blue) — market-open introduced it.
          The premarket scan didn&apos;t flag this ticker; the opening drive
          surfaced a fresh setup. Often the highest-volatility opportunities
          but also the highest-uncertainty.
        </li>
        <li>
          <strong>Premarket only</strong> (amber) — premarket flagged it but
          market-open dropped it. Usually because the underlying moved away
          from the planned entry, news invalidated the thesis, or the
          opening drive made the setup stale.
        </li>
      </ul>

      <h2>Grade delta — what counts as a step?</h2>
      <p>
        The grade scale is ordered (A+ &gt; A &gt; A− &gt; B+ &gt; B &gt; B− &gt;
        C+ &gt; C &gt; C− &gt; D+ &gt; D &gt; D− &gt; F). Each step is one slot
        on that ladder. So premarket A− to market-open A is ▲ 1 step; premarket
        B+ to market-open A− is ▲ 2 steps. Step counts give you a quick sense
        of how dramatically the routine&apos;s opinion changed between scans.
      </p>

      <h2>What &ldquo;Direction Δ&rdquo; tells you</h2>
      <ul>
        <li>
          <strong>same</strong> — strongest confirmation. Both scans agree on
          puts/calls/long/short. The trade is exactly as planned.
        </li>
        <li>
          <strong>flipped</strong> — opposite direction. Put → call or call →
          put. A strong reversal signal that something material happened at
          the open.
        </li>
        <li>
          <strong>→ avoid</strong> — premarket flagged a live trade;
          market-open downgraded it to AVOID. Treat as a kill.
        </li>
        <li>
          <strong>from avoid</strong> — premarket said AVOID; market-open
          promoted it into a live trade. The opening drive must have created
          a setup the premarket didn&apos;t see.
        </li>
      </ul>

      <h2>How this fits with the other tabs</h2>
      <p>
        Pre-market is the original plan. Market-Open is the post-open re-grade.
        Analysis is the side-by-side comparison + LLM narrative explaining
        what changed and why. Trade Cards is the final merged plan (with
        post-close outcome stamps at end of day). Scorecard is the cross-day
        aggregate. Each tab is a different lens on the same daily flow —
        Analysis is specifically about the 8:30 → 9:45 transition.
      </p>
    </LearnPageScaffold>
  );
}
